/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

module.exports = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually

  tutorialSidebar: [
    {
      type: "category",
      label: "BPL",
      items: [
        "intro",
        "gradelist",
        "customerlists",
        "production_forcast",
        {
          type: "category",
          label: "Factory",
          items: ["Factory/Barcode-Creation", "Factory/Factory-Exit"],
        },
        {
          type: "category",
          label: "Inventory",
          items: [
            "Inventory/store_entrance",
            "Inventory/store_exit",
            "Inventory/store_transfer",
          ],
        },
      ],
    },
    {
      type: "category",
      label: "Sales",
      items: ["Sales/bill_of_landing"],
    },
    {
      type: "category",
      label: "Report",
      items: ["Report/general"],
    },
    {
      type: "category",
      label: "User",
      items: ["User/profile"],
    },
  ],
};
